/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khangames_framework_gl_BufferUtils */

#ifndef _Included_com_khangames_framework_gl_BufferUtils
#define _Included_com_khangames_framework_gl_BufferUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_khangames_framework_gl_BufferUtils
 * Method:    copyJni
 * Signature: ([FLjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_com_khangames_framework_gl_BufferUtils_copyJni
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
